
import ez_setup
ez_setup.use_setuptools()

import sys, glob
from setuptools import setup, Extension

setup(name = "NW",
      ext_modules = [
          Extension('_NW', # Has to be prefixed with the underscore because this is the name generated by swig.
                    glob.glob('*.c'),
                    include_dirs=['.']
                    ),
        ]
      )


