
import ez_setup
ez_setup.use_setuptools()

import sys, glob
from setuptools import setup, Extension, find_packages

setup(name='SAPplugin-IM',
      version='1.0',
      description='IM plugin for SAP.',
      long_description='SAP interface for IM to use this for assigning posterior probabiliteis to an unsamples sister population the to the most likely from the database. ',
      author='Sang Chul Choi, Jody Hey, Kasper Munch',
      author_email='kaspermunch@berkeley.edu',
      packages = find_packages(exclude=['ez_setup']),
      entry_points = { 'sap.assignment': [ 'IM = IM', ], },
      ext_modules=[ Extension('_IM', # Has to be prefixed with the underscore because this is the name generated by swig.
                             #glob.glob('*.c[px][px]') + glob.glob('im/ima2-2.0/src/*.c'),
                             glob.glob('*.c') +          glob.glob('im/ima2-2.0/src/*.c'),
                             include_dirs=['im/ima2-2.0', 'im/ima2-2.0/src']
                             ) ]
      )



# maybe try extra_link_args.....
